//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPrep.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealAddOn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MealAddOn()
        {
            this.MealTransactionDetailAddOns = new HashSet<MealTransactionDetailAddOn>();
            this.ShoppingCartAddOns = new HashSet<ShoppingCartAddOn>();
        }
    
        public int MealAddOnId { get; set; }
        public int MealId { get; set; }
        public string MealAddOnName { get; set; }
        public decimal MealAddOnPrice { get; set; }
    
        public virtual Meal Meal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTransactionDetailAddOn> MealTransactionDetailAddOns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartAddOn> ShoppingCartAddOns { get; set; }
    }
}
