//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPrep.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShoppingCart()
        {
            this.ShoppingCartAddOns = new HashSet<ShoppingCartAddOn>();
        }
    
        public int CartId { get; set; }
        public string UserId { get; set; }
        public int MealId { get; set; }
        public int Qty { get; set; }
        public decimal Price { get; set; }
        public string PickupDelivery { get; set; }
        public Nullable<System.DateTime> PickupDeliveryDt { get; set; }
        public System.DateTime DateAdded { get; set; }
        public string RemoveIngredients { get; set; }
    
        public virtual Meal Meal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShoppingCartAddOn> ShoppingCartAddOns { get; set; }
    }
}
