//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPrep.Data.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealTransaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MealTransaction()
        {
            this.MealTransactionDetails = new HashSet<MealTransactionDetail>();
        }
    
        public int MealTransactionId { get; set; }
        public decimal Price { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreateDt { get; set; }
        public string TransactionId { get; set; }
        public string ResponseCode { get; set; }
        public string ResponseDescription { get; set; }
        public string AuthCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MealTransactionDetail> MealTransactionDetails { get; set; }
    }
}
