//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPrep.Data.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class MealRating
    {
        public int MealRatingId { get; set; }
        public int MealId { get; set; }
        public string UserId { get; set; }
        public int StarRating { get; set; }
        public string RatingComments { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDt { get; set; }
    
        public virtual Meal Meal { get; set; }
    }
}
