//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalPrep.Data.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.Meals = new HashSet<Meal>();
            this.VendorPayments = new HashSet<VendorPayment>();
        }
    
        public int VendorId { get; set; }
        public string UserId { get; set; }
        public string VendorName { get; set; }
        public string CompanyName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string Zip { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string VendorDescription { get; set; }
        public bool DeliveryAvailable { get; set; }
        public bool PickupAvailable { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string PlaceId { get; set; }
        public string FormattedAddress { get; set; }
        public string ImgSrc { get; set; }
        public bool IsApproved { get; set; }
        public string ApprovedById { get; set; }
        public System.DateTime SubmitDt { get; set; }
        public bool LicensedInState { get; set; }
        public string LicenseNo { get; set; }
        public string AboutYourself { get; set; }
        public string FavoriteThingsToCook { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meal> Meals { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorPayment> VendorPayments { get; set; }
    }
}
