// <auto-generated />
namespace LocalPrep.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddedCookingStyle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCookingStyle));
        
        string IMigrationMetadata.Id
        {
            get { return "202010081521511_AddedCookingStyle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
